### ISSUE TITLE
Way for stratum 1 to indicate type of reference source?

### ISSUE THREAD

**Issue by Artoria2e5** [ietf-wg-ntp/draft-ietf-ntp-ntpv5#6]
The bloom filter thing is awesome, but by using it over a list of refids we seems to have lost the functionality of running `ntpq` on a stratum 1 and asking it whether it's taking stuff from GPS, WWVB, or some other thing. I am not sure how important [these pregistered `refid` stuff](https://www.iana.org/assignments/ntp-parameters/ntp-parameters.xhtml#ntp-parameters-1) really are, as personally it's really just for curiosity.

I am not sure about the route to adding such a feature. I mean, the bloom sounds unneeded at stratum 1, but why contaminate two extension field types when you can make new ones?

**Comment by mlichvar** [comment]
`ntpq` and other implementation-specific protocols can still work even if NTPv5 doesn't directly provide this value.

A new extension field just for this value is certainly an option.

Another option is to map the string refids to the bloom filter as is already specified for NTPv5 clients using NTPv4 servers. An advantage of this approach would be that it could contain multiple refids on stratum 1 servers using multiple sources. A disadvantage is that you would have to iterate over a list of known values to detect their presence and the fact the stratum-1 servers would be required to provide this field (in current draft it's necessary only for stratum >1).
